
logging:
  level:
    .: ERROR
    org.springframework: ERROR
    com.pintailconsultingllc.microservices.profile: ERROR

spring:
  application:
    name: "Profile microservice"
  datasource:
    url: ${PROFILE_JDBC_URL}
    username: ${PROFILE_JDBC_USERNAME}
    password: ${PROFILE_JDBC_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  liquibase:
    enabled: false
    changeLog: classpath:db/db.changelog-master.xml

---

spring:
  profiles: local
  liquibase:
    enabled: false


logging:
  level:
    .: INFO
    org.springframework: INFO
    com.pintailconsultingllc.microservices.profile: INFO

